ergebnis/test-util

README.md
composer.json
src/Helper.php
test/Unit/HelperTest.php

Enhancement: Share localized Faker\Generator via faker()

---

test/Unit/Fixture/ExampleClass.php
test/Unit/Fixture/ExampleInterface.php
test/Unit/Fixture/ExampleTrait.php
test/Unit/HelperTest.php

Fix: Rename fixtures

---

README.md
src/Helper.php
test/Unit/Fixture/ClassImplementingInterface.php
test/Unit/Fixture/ClassNotImplementingInterface.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that a class implements an interface

---

test/Unit/HelperTest.php

Fix: Merge tests

---

test/Unit/Fixture/ClassExists/ExampleClass.php
test/Unit/Fixture/ClassExtends/ChildClass.php
test/Unit/Fixture/ClassExtends/ParentClass.php
test/Unit/Fixture/ClassExtends/UnrelatedClass.php
test/Unit/Fixture/ClassIsAbstractOrFinal/AbstractClass.php
test/Unit/Fixture/ClassIsAbstractOrFinal/FinalClass.php
test/Unit/Fixture/ClassIsAbstractOrFinal/NeitherAbstractNorFinalClass.php
test/Unit/Fixture/ClassUsesTrait/ClassNotUsingTrait.php
test/Unit/Fixture/ClassUsesTrait/ClassUsingTrait.php
test/Unit/Fixture/ClassUsesTrait/ExampleTrait.php
test/Unit/Fixture/ImplementsInterface/ClassImplementingInterface.php
test/Unit/Fixture/ImplementsInterface/ClassNotImplementingInterface.php
test/Unit/Fixture/ImplementsInterface/ExampleInterface.php
test/Unit/Fixture/InterfaceExists/ExampleInterface.php
test/Unit/Fixture/InterfaceExtends/ChildInterface.php
test/Unit/Fixture/InterfaceExtends/ParentInterface.php
test/Unit/Fixture/InterfaceExtends/UnrelatedInterface.php
test/Unit/Fixture/NotClass/ExampleInterface.php
test/Unit/Fixture/NotClass/ExampleTrait.php
test/Unit/Fixture/NotInterface/ExampleClass.php
test/Unit/Fixture/NotInterface/ExampleTrait.php
test/Unit/Fixture/NotTrait/ExampleClass.php
test/Unit/Fixture/NotTrait/ExampleInterface.php
test/Unit/Fixture/TraitExists/ExampleTrait.php
test/Unit/HelperTest.php

Fix: Reuse fixtures only where appropriate

---

composer.json

This PR
💁‍♂️ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.4.0...1.5.0.

Enhancement: Update localheinz/php-cs-fixer-config

---

composer.json

This PR
💁‍♂️ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.5.0...1.5.1.

Fix: Update localheinz/php-cs-fixer-config

---

.gitignore
.travis.yml
Makefile
composer.lock

Fix: Check in composer.lock

---

.travis.yml

Fix: Streamline Travis configuration across repositories

---

README.md
composer.json
composer.lock
src/Helper.php
test/Fixture/ClassesAreAbstractOrFinal/AbstractClass.php
test/Fixture/ClassesAreAbstractOrFinal/AbstractOrFinal/AbstractClass.php
test/Fixture/ClassesAreAbstractOrFinal/AbstractOrFinal/FinalClass.php
test/Fixture/ClassesAreAbstractOrFinal/FinalClass.php
test/Fixture/ClassesAreAbstractOrFinal/NotAllAbstractOrFinal/AbstractClass.php
test/Fixture/ClassesAreAbstractOrFinal/NotAllAbstractOrFinal/AlsoNeitherAbstractNorFinal.php
test/Fixture/ClassesAreAbstractOrFinal/NotAllAbstractOrFinal/FinalClass.php
test/Fixture/ClassesAreAbstractOrFinal/NotAllAbstractOrFinal/NeitherAbstractNorFinal.php
test/Unit/HelperTest.php
test/Unit/ProjectCodeTest.php

Enhancement: Allow to assert that classes in a directory are abstract or final

---

README.md
src/Helper.php
test/Fixture/ClassesSatisfySpecification/AnotherExampleClass.php
test/Fixture/ClassesSatisfySpecification/ExampleClass.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that classes in a directory satisfy a specification

---

README.md
composer.json
composer.lock
src/Helper.php

This PR
💁‍♂️ This just makes it less of a hassle using this package.

Fix: Require, do not suggest packages

---

README.md
src/Helper.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/AnotherExampleClass.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/ExampleClass.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/OneMoreExampleClass.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/Test/ExampleClassTest.php
test/Fixture/ClassesHaveTests/WithTests/AbstractClass.php
test/Fixture/ClassesHaveTests/WithTests/ExampleClass.php
test/Fixture/ClassesHaveTests/WithTests/ExampleInterface.php
test/Fixture/ClassesHaveTests/WithTests/ExampleTrait.php
test/Fixture/ClassesHaveTests/WithTests/Test/ExampleClassTest.php
test/Fixture/ClassesHaveTests/WithoutTests/AbstractClass.php
test/Fixture/ClassesHaveTests/WithoutTests/ExampleClass.php
test/Fixture/ClassesHaveTests/WithoutTests/ExampleInterface.php
test/Fixture/ClassesHaveTests/WithoutTests/ExampleTrait.php
test/Unit/HelperTest.php
test/Unit/ProjectCodeTest.php

Enhancement: Allow to assert that classes have tests

---

composer.json

Fix: Update keywords

---

src/Helper.php

This PR
💁‍♂️ Maybe this helps others if they want to use it.

Fix: Add docblocks with descriptions

---

composer.json

Fix: Do not optimize autoloader

---

composer.json
composer.lock

This PR
💁‍♂️ For reference, see https://github.com/localheinz/classy/compare/0.1.0...0.2.0.

Enhancement: Update localheinz/classy

---

src/Constraint/TraitExists.php
src/Helper.php
test/Unit/Constraint/AbstractTestCase.php
test/Unit/Constraint/TraitExistsTest.php
test/Unit/DataProvider.php
test/Unit/HelperTest.php

Enhancement: Extract TraitExists constraint

---

src/Constraint/ClassExists.php
src/Helper.php
test/Unit/Constraint/ClassExistsTest.php
test/Unit/DataProvider.php
test/Unit/HelperTest.php

Enhancement: Extract ClassExists constraint

---

README.md
src/Helper.php
test/Unit/HelperTest.php

Enhancement: Improve failure message of assertClassesHaveTests()

---

.gitignore
.travis.yml
Makefile
composer.json
composer.lock
infection.json

This PR
💁‍♂️ For reference, see https://infection.github.io.

Enhancement: Run mutation tests with infection/infection

---

src/Exception/NonExistentDirectory.php
src/Helper.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/HelperTest.php

Enhancement: Throw NonExistentDirectory exception

---

.github/CONTRIBUTING.md

Fix: Update CONTRIBUTING.md

---

.travis.yml

Enhancement: Run infection on PHP 7.2

---

src/Helper.php
test/Fixture/ClassesHaveTests/WithTests/Src/ExampleTest.php

Fix: Improve legibility

---

.travis.yml
composer.json
composer.lock

Fix: Drop support for PHP 7.0

---

README.md
src/Helper.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/Exception/NonExistentExcludeClassTest.php
test/Unit/HelperTest.php
test/Unit/ProjectCodeTest.php

This PR
Partially following #85.

Enhancement: Add return type declarations

---

composer.json
composer.lock

Fix: Allow installation of phpunit/phpunit:^7.0.0

---

.gitattributes
.travis.yml
Makefile
composer.json
composer.lock
phpstan.neon

Enhancement: Use phpstan/phpstan

---

.travis.yml
Makefile
test/AutoReview/SrcCodeTest.php
test/AutoReview/TestCodeTest.php
test/AutoReview/phpunit.xml

Enhancement: Split auto review tests from unit tests

---

.travis.yml
Makefile
composer.json
composer.lock
src/Helper.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/Exception/NonExistentExcludeClassTest.php

This PR
💁‍♂️ For reference, see
* https://github.com/infection/infection/compare/0.8.2...0.11.2
* https://github.com/phpstan/phpstan/compare/0.9.2...0.10.5
* https://github.com/phpstan/phpstan-phpunit/compare/0.9.4...0.10
* https://github.com/phpstan/phpstan-strict-rules/compare/0.9...0.10.1

Enhancement: Update infection/infection and phpstan/phpstan

---

.editorconfig
.gitattributes
.github/stale.yml
.gitignore
.php_cs
.travis.yml
Makefile
infection.json
phpstan.neon
test/AutoReview/phpunit.xml
test/Unit/phpunit.xml

Enhancement: Synchronize project tooling configuration with localheinz/repository

---

composer.lock

This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/7.4.3...7.5.0.

Enhancement: Update phpunit/phpunit

---

.github/workflows/continuous-integration.yml

Fix: Adjust MSI score

---

CHANGELOG.md
composer.json
composer.lock

Enhancement: Allow installation of phpunit/phpunit:^8.0.0

---

CHANGELOG.md
README.md

Fix: Example in README.md

---

.php_cs
.php_cs.fixture

Enhancement: Run php-cs-fixer on .php_cs.fixture

---

.php_cs
.php_cs.fixture
composer.json
composer.lock

Enhancement: Use ergebnis/php-cs-fixer-config

---

.dependabot/config.yml
.github/CONTRIBUTING.md
.github/settings.yml
.github/workflows/continuous-integration.yml
.github/workflows/stale.yml
Makefile
README.md
composer-require-checker.json
composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon

Enhancement: Synchronize with ergebnis/php-library-template

---

README.md

Fix: Labels

---

CHANGELOG.md

Fix: Add missing update instructions

---

composer.json
composer.lock
phpstan-baseline.neon
phpstan.neon
src/Helper.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/HelperTest.php

Enhancement: Update phpstan/phpstan and friends

---

composer.json
composer.lock

Enhancement: Require phpstan/phpstan-deprecation-rules

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Enhancement: Add support for PHP 8.0

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
composer.json
phpstan-baseline.neon
phpstan.neon
psalm-baseline.xml
src/DataProvider/BooleanProvider.php
src/Exception/EmptyValues.php
src/Helper.php
test/Unit/DataProvider/BooleanProviderTest.php
test/Unit/Exception/EmptyValuesTest.php
test/Unit/HelperTest.php

Enhancement: Implement BooleanProvider

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/StringProvider.php
test/Unit/DataProvider/StringProviderTest.php

Enhancement: Implement StringProvider

---

README.md

Fix: Remove empty list item

---

.github/workflows/integrate.yaml
Makefile
README.md
psalm-baseline.xml
src/DataProvider/StringProvider.php
test/Unit/DataProvider/StringProviderTest.php

Enhancement: Implement DataProvider\StringProvider::trimmed()

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/FloatProvider.php
test/Unit/DataProvider/FloatProviderTest.php

Enhancement: Implement DataProvider\FloatProvider

---

CHANGELOG.md
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/ResourceProvider.php
test/Unit/DataProvider/ResourceProviderTest.php

Enhancement: Implement DataProvider\ResourceProvider

---

README.md

Fix: Imports

---

.github/workflows/integrate.yaml

Fix: Use `--dry-run` option

---

.php-cs-fixer.fixture.php
.php-cs-fixer.php
test/Util/DataProvider/Specification/Closure.php
test/Util/DataProvider/Specification/Pattern.php

Enhancement: Use `Php74` rule set

---

CHANGELOG.md

Fix: `CHANGELOG.md`
