README.md
src/Helper.php
test/Unit/Fixture/AClass.php
test/Unit/Fixture/ATrait.php
test/Unit/Fixture/AnInterface.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that classes, interfaces, and traits exist

---

README.md
src/Helper.php
test/Unit/Fixture/AbstractClass.php
test/Unit/Fixture/FinalClass.php
test/Unit/Fixture/NonFinalClass.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that a class is abstract or final

---

README.md

Fix: Reword section about faker()

---

test/Unit/HelperTest.php

Fix: Rename test methods

---

README.md
src/Helper.php
test/Unit/Fixture/ClassExtendingParentClass.php
test/Unit/Fixture/ClassNotExtendingParentClass.php
test/Unit/Fixture/InterfaceExtendingParentInterface.php
test/Unit/Fixture/InterfaceNotExtendingParentInterface.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that classes and interfaces extend other classes and interfaces

---

README.md
src/Helper.php
test/Unit/Fixture/ClassNotUsingTrait.php
test/Unit/Fixture/ClassUsingTrait.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that a class uses a trait

---

src/Helper.php
test/Unit/HelperTest.php

Fix: Consistently end assertion messages with a period

---

README.md
src/Helper.php

Enhancement: Trigger E_USER_ERROR when fzaninotto/faker is not installed

---

README.md
src/Helper.php
test/Fixture/ClassSatisfiesSpecification/ExampleClass.php
test/Fixture/InterfaceSatisfiesSpecification/ExampleInterface.php
test/Fixture/TraitSatisfiesSpecification/ExampleTrait.php
test/Unit/HelperTest.php

Enhancement: Allow to assert that classes, interfaces, and traits satisfy specifications

---

composer.json

This PR
💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#optimize-autoloader.

Fix: Configure composer to optimize autoloader

---

src/Helper.php
test/Unit/HelperTest.php

This PR
Blocks https://github.com/localheinz/factory-girl-definition/pull/15.

Fix: Ignore non-existent exclude classes

---

.travis.yml

This PR
💁‍♂️ For reference, see https://docs.travis-ci.com/user/build-stages/.

Enhancement: Use stages

---

composer.json
composer.lock

This PR
💁‍♂️ There's no reason not to use the latest versions.

Fix: Increase version requirement for fzaninotto/faker

---

src/Helper.php

Fix: Add missing throws annotation

---

composer.json
composer.lock
src/Helper.php

This PR
💁‍♂️ For reference, see https://github.com/localheinz/classy.

Enhancement: Use localheinz/classy instead of zendframework/zend-file

---

test/Unit/HelperTest.php

Fix: Use key when yielding data in data providers

---

README.md
src/Helper.php
test/Fixture/ClassyConstructsSatisfySpecification/AnotherExampleClass.php
test/Fixture/ClassyConstructsSatisfySpecification/ExampleClass.php
test/Unit/HelperTest.php

Fix: Rename assertClassesSatisfySpecification() to assertClassyConstructsSatisfySpecification()

---

test/Unit/HelperTest.php

Fix: Add missing test

---

README.md
src/Helper.php
test/Fixture/ClassIsFinal/AbstractClass.php
test/Fixture/ClassIsFinal/FinalClass.php
test/Fixture/ClassIsFinal/NeitherAbstractNorFinalClass.php
test/Unit/HelperTest.php
test/Unit/ProjectCodeTest.php

Enhancement: Allow to assert that a class is final

---

src/Helper.php
test/Unit/HelperTest.php

This PR
💁‍♂️ This makes the transition easier when actually extracting constraints.

Fix: Adjust assertion messages

---

src/Constraint/InterfaceExists.php
src/Helper.php
test/Unit/Constraint/InterfaceExistsTest.php
test/Unit/DataProvider.php
test/Unit/HelperTest.php

Enhancement: Extract InterfaceExists constraint

---

test/Unit/Constraint/ClassExistsTest.php
test/Unit/Constraint/InterfaceExistsTest.php
test/Unit/Constraint/TraitExistsTest.php

Fix: Consistently use if instead of when

---

README.md
src/Helper.php
test/Fixture/ClassIsAbstract/AbstractClass.php
test/Fixture/ClassIsAbstract/ConcreteClass.php
test/Unit/HelperTest.php
test/Unit/ProjectCodeTest.php

Enhancement: Allow to assert that a class is abstract

---

test/Unit/ProjectCodeTest.php

Fix: Remove reference to non-existent class

---

src/Helper.php

This PR
💁‍♂️ For reference, see https://youtrack.jetbrains.com/issue/WI-1730.

Fix: Use mixin annotation to indicate that TestCase is mixed in

---

README.md

This PR
Related to https://github.com/opencfp/opencfp/issues/882#issuecomment-350028160.
/cc @keradus

Fix: Add credits for ProjectCodeTest

---

Makefile

Fix: Remove irrelevant target from Makefile

---

test/Unit/HelperTest.php

Fix: Assert that helper methods are final and protected

---

src/Helper.php
test/Unit/HelperTest.php

Enhancement: Reject non-existent exclude class name

---

src/Exception/NonExistentExcludeClass.php
src/Helper.php
test/Unit/Exception/NonExistentExcludeClassTest.php
test/Unit/HelperTest.php

Enhancement: Throw NonExistentExcludeClass exception

---

src/Exception/InvalidExcludeClassName.php
src/Helper.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/HelperTest.php

Enhancement: Throw InvalidExcludeClassName exception

---

src/Helper.php

Fix: Remove mixin annotation

---

test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/Src/AnotherExampleClass.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/Src/ExampleClass.php
test/Fixture/ClassesHaveTests/NotAllClassesHaveTests/Src/OneMoreExampleClass.php
test/Fixture/ClassesHaveTests/WithTests/Src/AbstractClass.php
test/Fixture/ClassesHaveTests/WithTests/Src/ExampleClass.php
test/Fixture/ClassesHaveTests/WithTests/Src/ExampleInterface.php
test/Fixture/ClassesHaveTests/WithTests/Src/ExampleTrait.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/AbstractClass.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/ExampleClass.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/ExampleInterface.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/ExampleTrait.php
test/Unit/HelperTest.php

This PR
💁‍♂️ While there are projects that have their test classes within the same namespace as their production classes, I usually don't.

Fix: Test fixture directories

---

src/Helper.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/AnotherExampleClass.php
test/Fixture/ClassesHaveTests/WithoutTests/Src/OneMoreExampleClass.php
test/Fixture/ClassesHaveTests/WithoutTests/Test/AnotherExampleClassTest.php
test/Fixture/ClassesHaveTests/WithoutTests/Test/OneMoreExampleClassTest.php
test/Unit/HelperTest.php

Fix: Test classes need to be concrete and extend from PHPUnit\Framework\TestCase

---

test/Fixture/ClassesHaveTests/WithoutTests/Src/YetAnotherExampleClass.php
test/Unit/HelperTest.php

Enhancement: Assert that concrete class with private constructor needs a test

---

.travis.yml
Makefile
composer.json
composer.lock

Enhancement: Run 'composer normalize'

---

.travis.yml
Makefile

This PR
Follows #94.
💁‍♂️ For reference, see https://github.com/composer/composer/compare/1.7.0...1.7.1.

Fix: Use latest version of composer

---

composer.json
composer.lock

This PR
Related to https://github.com/sebastianbergmann/phpunit/issues/3354.

Fix: Disallow installation of phpunit/phpunit:7.4.1

---

composer.json
composer.lock

Fix: Remove upper constraint for phpunit/phpunit

---

.github/CONTRIBUTING.md
Makefile

Fix: Let it target depend on stan

---

composer.json
composer.lock
phpstan.neon
test/Unit/HelperTest.php

Enhancement: Require localheinz/phpstan-rules

---

CHANGELOG.md
src/Helper.php
test/AutoReview/SrcCodeTest.php
test/AutoReview/TestCodeTest.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/Exception/NonExistentExcludeClassTest.php
test/Unit/HelperTest.php

Fix: Methods can be static

---

CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for phpunit/phpunit:^6.0.0

---

.github/settings.yml

Fix: Do not require builds for unsupported PHP 7.1 to pass

---

.dependabot/config.yml

Fix: Exclude phpunit/phpunit from dependabot updates

---

README.md

Fix: Remove mention of Refinery29

---

composer.json
composer.lock
src/Helper.php

Enhancement: Use ergebnis/classy instead of localheinz/classy

---

.php_cs
.php_cs.fixture
CHANGELOG.md
README.md
composer.json
src/Exception/InvalidExcludeClassName.php
src/Exception/NonExistentDirectory.php
src/Exception/NonExistentExcludeClass.php
src/Helper.php
test/AutoReview/SrcCodeTest.php
test/AutoReview/TestCodeTest.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/Exception/NonExistentExcludeClassTest.php
test/Unit/HelperTest.php

Fix: References after move to @ergebnis

---

composer.json
composer.lock
phpstan-baseline.neon

Fix: Require phpstan/extension-installer

---

.dependabot/config.yml
.github/settings.yml
.github/workflows/continuous-integration.yml
Makefile
README.md

Enhancement: Synchronize with ergebnis/php-library-template

---

.php_cs
.php_cs.fixture
composer.json
composer.lock

Enhancement: Use ergebnis/php-cs-fixer-config instead of localheinz/php-cs-fixer-config

---

CHANGELOG.md
composer.json
composer.lock

Fix: Use caret operator

---

.github/settings.yml

Fix: Require tests for PHP 8.0 to pass

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/NullProvider.php
test/Unit/DataProvider/NullProviderTest.php

Enhancement: Implement NullProvider

---

phpstan-baseline.neon
src/DataProvider/BooleanProvider.php
src/DataProvider/NullProvider.php
src/DataProvider/StringProvider.php
src/Helper.php
test/Unit/HelperTest.php

Fix: Rename methods

---

README.md

Enhancement: Provide example for composition of data providers

---

README.md

This PR
Follows #326.
Follows #328.

Fix: Add StringProvider to list in README.md

---

.github/workflows/integrate.yaml
Makefile
phpstan-baseline.neon
phpstan.neon
test/Unit/DataProvider/AbstractProviderTestCase.php
test/Unit/DataProvider/BooleanProviderTest.php
test/Unit/DataProvider/NullProviderTest.php
test/Unit/DataProvider/StringProviderTest.php

Fix: Test data providers directly

---

.github/workflows/integrate.yaml
CHANGELOG.md
Makefile
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/IntProvider.php
test/Unit/DataProvider/IntProviderTest.php

Enhancement: Implement IntProvider

---

.github/workflows/integrate.yaml
Makefile
phpstan-baseline.neon
psalm-baseline.xml
test/Unit/DataProvider/AbstractProviderTestCase.php
test/Unit/DataProvider/IntProviderTest.php
test/Unit/DataProvider/StringProviderTest.php

Fix: Test provided values individually

---

README.md
src/DataProvider/StringProvider.php
test/Unit/DataProvider/StringProviderTest.php

Fix: Provide all kinds of string values from StringProvider::arbitrary()

---

README.md

Fix: Add IntProvider to list

---

.php_cs
CHANGELOG.md
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/ObjectProvider.php
test/Unit/DataProvider/ObjectProviderTest.php
test/Util/DataProvider/Specification/Equal.php

Enhancement: Implement DataProvider\ObjectProvider

---

README.md

Fix: Make clear, values are not empty

---

CHANGELOG.md
composer.json
composer.lock

Fix: Use fakerphp/faker instead of fzaninotto/faker

---

test/Unit/DataProvider/StringProviderTest.php

Fix: Test method name

---

CHANGELOG.md
README.md
psalm-baseline.xml
src/DataProvider/StringProvider.php
test/Unit/DataProvider/StringProviderTest.php

This PR
💁‍♂️ This can be useful for testing a method that should reject `string`s containing any whitespace characters.

Enhancement: Add DataProvider\StringProvider::withWhitespace()

---

CHANGELOG.md
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/DataProvider/BoolProvider.php
src/DataProvider/FloatProvider.php
src/DataProvider/IntProvider.php
src/DataProvider/NullProvider.php
src/DataProvider/ObjectProvider.php
src/DataProvider/ResourceProvider.php
src/DataProvider/StringProvider.php

Fix: Deprecate data providers

---

.github/workflows/integrate.yaml
Makefile

Fix: Do not cache cache directory for `phpstan/phpstan` and `vimeo/psalm`

---

.php_cs
.php_cs.fixture
src/DataProvider/StringProvider.php
src/Exception/InvalidExcludeClassName.php
src/Exception/NonExistentDirectory.php
src/Exception/NonExistentExcludeClass.php
src/Helper.php
test/Unit/DataProvider/AbstractProviderTestCase.php
test/Unit/Exception/InvalidExcludeClassNameTest.php
test/Unit/Exception/NonExistentDirectoryTest.php
test/Unit/Exception/NonExistentExcludeClassTest.php
test/Unit/HelperTest.php

Enhancement: Use `Php73` rule set

---

.gitattributes
.github/workflows/integrate.yaml
.github/workflows/renew.yaml
.php-cs-fixer.fixture.php
.php-cs-fixer.php
Makefile

Fix: Rename `.php_cs` to `.php-cs-fixer.php`

---

Makefile

Fix: Run `friendsofphp/php-cs-fixer` on fixtures

---

.github/CONTRIBUTING.md
.github/workflows/integrate.yaml

Fix: Use Xdebug instead of pcov for collecting code coverage

---

CHANGELOG.md
README.md
phpstan-baseline.neon
psalm-baseline.xml
src/Helper.php

Fix: Deprecate assertions

---

CHANGELOG.md
phpstan-baseline.neon
psalm-baseline.xml
src/Helper.php

Fix: Deprecate provide methods
